In [14]:
import sys
import os
print(sys.executable)

c:\Users\Ravichandran\OneDrive\Desktop\Ml Alogiritms dally progress\.venv\Scripts\python.exe

In [15]:
print(os.getcwd())
print(os.listdir())

c:\Users\Ravichandran\OneDrive\Desktop\fir crime type prediction model\data_cleane_files
['dataset_clean1.ipynb', 'dataset_clean2.ipynb', 'dataset_clean3.ipynb']

In [16]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

In [17]:
# load annotations
import json
with open(r"C:\Users\Ravichandran\OneDrive\Desktop\FIR_details.json") as f:
    data = json.load(f)

In [18]:
# group by imgae_id
from collections import defaultdict
grouped = defaultdict(list)

for row in data:
    grouped[row['image_id']].append(row)

In [19]:
records = []

for image_id, rows in grouped.items():
    texts  = [r['text'] for r in rows]
    ocr_text = " ".join(texts)
    ipc = [r['text'] for r in rows if r["category_id"] == 2]
    ps = [r['text'] for r in rows if r['category_id'] == 0]
    year= [r['text'] for r in rows if r['category_id'] == 1]

    records.append({
        'image_id': image_id,
        'ocr_text':ocr_text,
        'ipc_sections': ipc,
        'police_station':ps[0] if ps else None,
        'year':year[0] if year else None,
        'source':'FIR_ICDAR',
})

In [20]:
crime = pd.DataFrame(records)

In [21]:
crime.head(10)

,image_id,ocr_text,ipc_sections,police_station,year,source
0,452,2019 Electronics Complex 420/406/34 Ipc.,[420/406/34 Ipc.],Electronics Complex,2019,FIR_ICDAR
1,563,2017 2017 2017 Women Kamaljit Kaur Women 2017,[],Women,2017,FIR_ICDAR
2,143,2018 Baguiati Sanjukta Ghoshal 135(I)(A) Of E...,"[135(I)(A) Of Electricity Act, 2003]",Baguiati,2018,FIR_ICDAR
3,130,Partha Paul Baguiati 2021 341/323/506/34 Ipc ...,[341/323/506/34 Ipc],Baguiati,2021,FIR_ICDAR
4,144,2019 Baguiati 341/186/188/506/34 Ipc Si Jayan...,[341/186/188/506/34 Ipc],Baguiati,2019,FIR_ICDAR
5,217,Baguiati Md. Goni 2018 Baguiati,[],Baguiati,2018,FIR_ICDAR
6,169,Baguiati 341/325/34 Ipc 2018 Fatema Bibi,[341/325/34 Ipc],Baguiati,2018,FIR_ICDAR
7,377,Bikash Singha Roy Eco Park 2020 406/420/34 I...,[406/420/34 Ipc],Eco Park,2020,FIR_ICDAR
8,170,2019 Baguiati Kalpana Singh 498A Ipc,[498A Ipc],Baguiati,2019,FIR_ICDAR
9,235,Bidhannagar North 419/420/406 Ipc 2017 Bhaska...,[419/420/406 Ipc],Bidhannagar North,2017,FIR_ICDAR

In [22]:
crime.columns

Index(['image_id', 'ocr_text', 'ipc_sections', 'police_station', 'year',
       'source'],
      dtype='object')

In [23]:
crime.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 544 entries, 0 to 543
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   image_id        544 non-null    int64
 1   ocr_text        544 non-null    object
 2   ipc_sections    544 non-null    object
 3   police_station  496 non-null    object
 4   year            479 non-null    object
 5   source          544 non-null    object
dtypes: int64(1), object(5)
memory usage: 25.6+ KB

In [24]:
crime.describe()

         image_id
count  544.000000
mean   276.645221
std    161.293428
min      0.000000
25%    137.750000
50%    276.500000
75%    412.250000
max    568.000000

In [25]:
crime.isnull().sum()

image_id           0
ocr_text           0
ipc_sections       0
police_station    48
year              65
source             0
dtype: int64

In [26]:
crime['ocr_len'] = crime['ocr_text'].fillna("").str.split().str.len()
crime = crime[crime['ocr_len']>0]

In [27]:
crime.head()

,image_id,ocr_text,ipc_sections,police_station,year,source,ocr_len
0,452,2019 Electronics Complex 420/406/34 Ipc.,[420/406/34 Ipc.],Electronics Complex,2019,FIR_ICDAR,5
1,563,2017 2017 2017 Women Kamaljit Kaur Women 2017,[],Women,2017,FIR_ICDAR,8
2,143,2018 Baguiati Sanjukta Ghoshal 135(I)(A) Of E...,"[135(I)(A) Of Electricity Act, 2003]",Baguiati,2018,FIR_ICDAR,9
3,130,Partha Paul Baguiati 2021 341/323/506/34 Ipc ...,[341/323/506/34 Ipc],Baguiati,2021,FIR_ICDAR,7
4,144,2019 Baguiati 341/186/188/506/34 Ipc Si Jayan...,[341/186/188/506/34 Ipc],Baguiati,2019,FIR_ICDAR,10

In [28]:
crime.shape

(544, 7)

In [29]:
crime['ocr_len'].describe()

count    544.000000
mean       8.678309
std        4.562378
min        1.000000
25%        6.000000
50%        8.000000
75%       10.000000
max       39.000000
Name: ocr_len, dtype: float64

In [31]:
crime['ocr_text'] = crime['ocr_text'].astype(str).str.strip()
crime = crime[crime['ocr_text'] != ""]

In [32]:
crime

,image_id,ocr_text,ipc_sections,police_station,year,source,ocr_len
0,452,2019 Electronics Complex 420/406/34 Ipc.,[420/406/34 Ipc.],Electronics Complex,2019,FIR_ICDAR,5
1,563,2017 2017 2017 Women Kamaljit Kaur Women 2017,[],Women,2017,FIR_ICDAR,8
2,143,2018 Baguiati Sanjukta Ghoshal 135(I)(A) Of E...,"[135(I)(A) Of Electricity Act, 2003]",Baguiati,2018,FIR_ICDAR,9
3,130,Partha Paul Baguiati 2021 341/323/506/34 Ipc ...,[341/323/506/34 Ipc],Baguiati,2021,FIR_ICDAR,7
4,144,2019 Baguiati 341/186/188/506/34 Ipc Si Jayan...,[341/186/188/506/34 Ipc],Baguiati,2019,FIR_ICDAR,10
...,...,...,...,...,...,...,...
539,335,2020 Ritesh R Agarwal 408/419/420/120B Ipc Cyb...,[408/419/420/120B Ipc],Cyber-Crime,2020,FIR_ICDAR,8
540,263,279/333/353/114/34 Ipc 2017 Bidhannagar North ...,[279/333/353/114/34 Ipc],Bidhannagar North,2017,FIR_ICDAR,7
541,110,Baguiati 448/323/325/506 Ipc Chaina Hazra 201...,[448/323/325/506 Ipc],Baguiati,2018,FIR_ICDAR,8
542,276,Shibani Saha Chowdhury 2017 420/406 Ipc,[420/406 Ipc],None,2017,FIR_ICDAR,6
543,19,Azizul Haque Tarafdar 2018 Airport Azizul Haq...,[],Airport,2018,FIR_ICDAR,8

In [37]:
crime.to_csv('dataset_c_fir_ocr.csv', index=False)