## Dataset-B: FIR structured metadata for validation only Not use for training

In [25]:
import os
import sys
print(sys.executable)

c:\Users\Ravichandran\OneDrive\Desktop\Ml Alogiritms dally progress\.venv\Scripts\python.exe

In [26]:
os.listdir()

['.vscode',
 'data',
 'dataset_clean2.ipynb',
 'data_cleane_files',
 'Data_pipeline']

In [27]:
import os
print(os.getcwd())

c:\Users\Ravichandran\OneDrive\Desktop\fir crime type prediction model

In [28]:
import os

print(os.getcwd())
print(os.listdir())

c:\Users\Ravichandran\OneDrive\Desktop\fir crime type prediction model
['.vscode', 'data', 'dataset_clean2.ipynb', 'data_cleane_files', 'Data_pipeline']

In [29]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [30]:


crime = pd.read_csv("data/raw/FIR_Details_Data.csv")
crime = crime.copy()

C:\Users\Ravichandran\AppData\Local\Temp\ipykernel_21336\526679228.py:1: DtypeWarning: Columns (15) have mixed types. Specify dtype option on import or set low_memory=False.
  crime = pd.read_csv("data/raw/FIR_Details_Data.csv")

In [31]:
crime.head()

,District_Name,UnitName,FIR_YEAR,FIR_MONTH,Offence_Duration,FIR_Day,FIR Type,FIR_Stage,Complaint_Mode,CrimeGroup_Name,...,Girl,Age 0,VICTIM COUNT,Accused Count,Arrested Male,Arrested Female,Arrested Count\tNo.,Accused_ChargeSheeted Count,Conviction Count,Unit_ID
0,Bagalkot,Amengad PS,2016,1,0,5,Non Heinous,Dis/Acq,Written,POCSO,...,1,0,0,1,1,0,1,1,0,1245
1,Bagalkot,Amengad PS,2016,1,0,12,Non Heinous,Convicted,Sue-moto by Police,KARNATAKA POLICE ACT 1963,...,0,0,0,5,5,0,5,5,2,1245
2,Bagalkot,Amengad PS,2016,1,0,12,Non Heinous,Convicted,Sue-moto by Police,KARNATAKA POLICE ACT 1963,...,0,0,0,1,1,0,1,1,0,1245
3,Bagalkot,Amengad PS,2016,1,0,15,Non Heinous,Convicted,Written,MOTOR VEHICLE ACCIDENTS NON-FATAL,...,0,1,0,1,1,0,1,1,0,1245
4,Bagalkot,Amengad PS,2016,1,0,18,Heinous,Pending Trial,Written,MOTOR VEHICLE ACCIDENTS FATAL,...,0,0,0,1,1,0,1,1,0,1245

In [32]:
crime.shape

(1674734, 34)

In [33]:
crime.head(2).T

,0,1
District_Name,Bagalkot,Bagalkot
UnitName,Amengad PS,Amengad PS
FIR_YEAR,2016,2016
FIR_MONTH,1,1
Offence_Duration,0,0
FIR_Day,5,12
FIR Type,Non Heinous,Non Heinous
FIR_Stage,Dis/Acq,Convicted
Complaint_Mode,Written,Sue-moto by Police
CrimeGroup_Name,POCSO,KARNATAKA POLICE ACT 1963
CrimeHead_Name,Others,Street Gambling (87)
Latitude,NaN,NaN
Longitude,NaN,NaN
ActSection,PROTECTION OF CHILDREN FROM SEXUAL OFFENCES AC...,"KARNATAKA POLICE ACT, 1963 U/s: 87"
IOName,R S BIRADAR (PI),G.H.KUPPI (PSI)
KGID,1898733,1332599
Internal_IO,42900007,123600010
Place of Offence,"KAMATAGI BUS STAND, KAMATAGI BUS STAND","RAKKASAGI VILLEGE IN FRONT MOUNESHWAR TEMPEL, ..."
Distance from PS,WEST FROM PS 12 KM,WEST FROM PS 2 KM
Beat_Name,RURAL BEAT NO 13,RURAL BEAT NO 6
Village_Area_Name,KAMATAGI,SULEBAVI
Male,0,0
Female,0,0
Boy,0,0
Girl,1,0
Age 0,0,0
VICTIM COUNT,0,0
Accused Count,1,5
Arrested Male,1,5
Arrested Female,0,0
Arrested Count\tNo.,1,5
Accused_ChargeSheeted Count,1,5
Conviction Count,0,2
Unit_ID,1245,1245

In [34]:
crime.columns

Index(['District_Name', 'UnitName', 'FIR_YEAR', 'FIR_MONTH',
       'Offence_Duration', 'FIR_Day', 'FIR Type', 'FIR_Stage',
       'Complaint_Mode', 'CrimeGroup_Name', 'CrimeHead_Name', 'Latitude',
       'Longitude', 'ActSection', 'IOName', 'KGID', 'Internal_IO',
       'Place of Offence', 'Distance from PS', 'Beat_Name',
       'Village_Area_Name', 'Male', 'Female', 'Boy', 'Girl', 'Age 0',
       'VICTIM COUNT', 'Accused Count', 'Arrested Male', 'Arrested Female',
       'Arrested Count\tNo.', 'Accused_ChargeSheeted Count',
       'Conviction Count', 'Unit_ID'],
      dtype='object')

In [35]:
crime.isnull().sum()

District_Name                        0
UnitName                             0
FIR_YEAR                             0
FIR_MONTH                            0
Offence_Duration                     0
FIR_Day                              0
FIR Type                             0
FIR_Stage                            0
Complaint_Mode                       0
CrimeGroup_Name                      0
CrimeHead_Name                       0
Latitude                       1166600
Longitude                      1166635
ActSection                           0
IOName                               0
KGID                                 0
Internal_IO                          0
Place of Offence                     0
Distance from PS                     0
Beat_Name                            0
Village_Area_Name                    0
Male                                 0
Female                               0
Boy                                  0
Girl                                 0
Age 0                                0
VICTIM COUNT                         0
Accused Count                        0
Arrested Male                        0
Arrested Female                      0
Arrested Count\tNo.                  0
Accused_ChargeSheeted Count          0
Conviction Count                     0
Unit_ID                              0
dtype: int64

In [36]:
df_b_core = crime[
    [
        "District_Name", "UnitName", "FIR_YEAR", "FIR_MONTH", "FIR_Day",
        "FIR Type", "FIR_Stage", "Complaint_Mode",
        "CrimeGroup_Name", "CrimeHead_Name",
        "ActSection", "Place of Offence", "Distance from PS",
        "Male", "Female", "Boy", "Girl", "VICTIM COUNT",
        "Accused Count", "Arrested Count\tNo.",
        "Accused_ChargeSheeted Count", "Conviction Count", "Unit_ID"
    ]
]

In [37]:
df_b_core.shape

(1674734, 23)

In [39]:
crime.drop(['IOName','KGID','Internal_IO','Beat_Name','Village_Area_Name','Longitude','Latitude'],axis=1 , inplace=True)

In [40]:
crime.head()

,District_Name,UnitName,FIR_YEAR,FIR_MONTH,Offence_Duration,FIR_Day,FIR Type,FIR_Stage,Complaint_Mode,CrimeGroup_Name,...,Girl,Age 0,VICTIM COUNT,Accused Count,Arrested Male,Arrested Female,Arrested Count\tNo.,Accused_ChargeSheeted Count,Conviction Count,Unit_ID
0,Bagalkot,Amengad PS,2016,1,0,5,Non Heinous,Dis/Acq,Written,POCSO,...,1,0,0,1,1,0,1,1,0,1245
1,Bagalkot,Amengad PS,2016,1,0,12,Non Heinous,Convicted,Sue-moto by Police,KARNATAKA POLICE ACT 1963,...,0,0,0,5,5,0,5,5,2,1245
2,Bagalkot,Amengad PS,2016,1,0,12,Non Heinous,Convicted,Sue-moto by Police,KARNATAKA POLICE ACT 1963,...,0,0,0,1,1,0,1,1,0,1245
3,Bagalkot,Amengad PS,2016,1,0,15,Non Heinous,Convicted,Written,MOTOR VEHICLE ACCIDENTS NON-FATAL,...,0,1,0,1,1,0,1,1,0,1245
4,Bagalkot,Amengad PS,2016,1,0,18,Heinous,Pending Trial,Written,MOTOR VEHICLE ACCIDENTS FATAL,...,0,0,0,1,1,0,1,1,0,1245

In [42]:
crime.columns.shape

(27,)

In [43]:
crime.columns

Index(['District_Name', 'UnitName', 'FIR_YEAR', 'FIR_MONTH',
       'Offence_Duration', 'FIR_Day', 'FIR Type', 'FIR_Stage',
       'Complaint_Mode', 'CrimeGroup_Name', 'CrimeHead_Name', 'ActSection',
       'Place of Offence', 'Distance from PS', 'Male', 'Female', 'Boy', 'Girl',
       'Age 0', 'VICTIM COUNT', 'Accused Count', 'Arrested Male',
       'Arrested Female', 'Arrested Count\tNo.', 'Accused_ChargeSheeted Count',
       'Conviction Count', 'Unit_ID'],
      dtype='object')

In [44]:
crime.drop(['Offence_Duration','Place of Offence','Distance from PS','Male', 'Female', 'Boy', 'Girl','Age 0','Arrested Male',
       'Arrested Female', 'Arrested Count\tNo.','Accused_ChargeSheeted Count','Unit_ID'],axis=1 , inplace=True)

In [45]:
crime.head()

,District_Name,UnitName,FIR_YEAR,FIR_MONTH,FIR_Day,FIR Type,FIR_Stage,Complaint_Mode,CrimeGroup_Name,CrimeHead_Name,ActSection,VICTIM COUNT,Accused Count,Conviction Count
0,Bagalkot,Amengad PS,2016,1,5,Non Heinous,Dis/Acq,Written,POCSO,Others,PROTECTION OF CHILDREN FROM SEXUAL OFFENCES AC...,0,1,0
1,Bagalkot,Amengad PS,2016,1,12,Non Heinous,Convicted,Sue-moto by Police,KARNATAKA POLICE ACT 1963,Street Gambling (87),"KARNATAKA POLICE ACT, 1963 U/s: 87",0,5,2
2,Bagalkot,Amengad PS,2016,1,12,Non Heinous,Convicted,Sue-moto by Police,KARNATAKA POLICE ACT 1963,Gambling - Matka (78 Class C),"KARNATAKA POLICE ACT, 1963 U/s: 78(3)",0,1,0
3,Bagalkot,Amengad PS,2016,1,15,Non Heinous,Convicted,Written,MOTOR VEHICLE ACCIDENTS NON-FATAL,National Highways,"IPC 1860 U/s: 338,337,279",0,1,0
4,Bagalkot,Amengad PS,2016,1,18,Heinous,Pending Trial,Written,MOTOR VEHICLE ACCIDENTS FATAL,Other Roads,"IPC 1860 U/s: 304(A),279",0,1,0

In [58]:
crime.columns

Index(['District_Name', 'UnitName', 'FIR_YEAR', 'FIR_MONTH', 'FIR_Day',
       'FIR Type', 'FIR_Stage', 'Complaint_Mode', 'CrimeGroup_Name',
       'CrimeHead_Name', 'ActSection', 'VICTIM COUNT', 'Accused Count',
       'Conviction Count'],
      dtype='object')

In [50]:
crime.columns.shape

(14,)

In [64]:
crime.isnull().mean().sort_values(ascending=False).head(15)

district_name       0.0
unitname            0.0
fir_year            0.0
fir_month           0.0
fir_day             0.0
fir_type            0.0
fir_stage           0.0
complaint_mode      0.0
crimegroup_name     0.0
crimehead_name      0.0
actsection          0.0
victim_count        0.0
accused_count       0.0
conviction_count    0.0
dtype: float64

In [59]:
# columns fixing 
crime.columns=(crime.columns.str.strip().str.lower().str.replace(" ","_").str.replace("\t",""))

In [61]:
crime.head()

,district_name,unitname,fir_year,fir_month,fir_day,fir_type,fir_stage,complaint_mode,crimegroup_name,crimehead_name,actsection,victim_count,accused_count,conviction_count
0,Bagalkot,Amengad PS,2016,1,5,Non Heinous,Dis/Acq,Written,POCSO,Others,PROTECTION OF CHILDREN FROM SEXUAL OFFENCES AC...,0,1,0
1,Bagalkot,Amengad PS,2016,1,12,Non Heinous,Convicted,Sue-moto by Police,KARNATAKA POLICE ACT 1963,Street Gambling (87),"KARNATAKA POLICE ACT, 1963 U/s: 87",0,5,2
2,Bagalkot,Amengad PS,2016,1,12,Non Heinous,Convicted,Sue-moto by Police,KARNATAKA POLICE ACT 1963,Gambling - Matka (78 Class C),"KARNATAKA POLICE ACT, 1963 U/s: 78(3)",0,1,0
3,Bagalkot,Amengad PS,2016,1,15,Non Heinous,Convicted,Written,MOTOR VEHICLE ACCIDENTS NON-FATAL,National Highways,"IPC 1860 U/s: 338,337,279",0,1,0
4,Bagalkot,Amengad PS,2016,1,18,Heinous,Pending Trial,Written,MOTOR VEHICLE ACCIDENTS FATAL,Other Roads,"IPC 1860 U/s: 304(A),279",0,1,0

In [62]:
crime['fir_year']=crime['fir_year'].astype(int)
crime['fir_month']=crime['fir_month'].astype(int)
crime['fir_year']=crime['fir_year'].astype(int)

In [67]:
crime.isnull().sum()

district_name       0
unitname            0
fir_year            0
fir_month           0
fir_day             0
fir_type            0
fir_stage           0
complaint_mode      0
crimegroup_name     0
crimehead_name      0
actsection          0
victim_count        0
accused_count       0
conviction_count    0
dtype: int64

In [66]:
crime.to_csv('dataset_B_karnataka_fir.csv', index=False)